# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Viewer_pruebas.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1918, 1031)
        MainWindow.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(320, 140, 761, 701))
        self.Image.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Image.setText("")
        self.Image.setScaledContents(True)
        self.Image.setObjectName("Image")
        self.ROI = QtWidgets.QLabel(self.centralwidget)
        self.ROI.setGeometry(QtCore.QRect(320, 120, 761, 701))
        self.ROI.setText("")
        self.ROI.setTextFormat(QtCore.Qt.PlainText)
        self.ROI.setObjectName("ROI")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 32, 1851, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 121, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_OpenFile = QtWidgets.QToolButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_OpenFile.sizePolicy().hasHeightForWidth())
        self.btn_OpenFile.setSizePolicy(sizePolicy)
        self.btn_OpenFile.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_OpenFile.setSizeIncrement(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_OpenFile.setIcon(icon)
        self.btn_OpenFile.setIconSize(QtCore.QSize(25, 25))
        self.btn_OpenFile.setObjectName("btn_OpenFile")
        self.horizontalLayout.addWidget(self.btn_OpenFile)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 291, 891))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_Left = QtWidgets.QToolButton(self.layoutWidget1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/arrow-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Left.setIcon(icon1)
        self.btn_Left.setIconSize(QtCore.QSize(25, 25))
        self.btn_Left.setObjectName("btn_Left")
        self.horizontalLayout_2.addWidget(self.btn_Left)
        self.btn_Right = QtWidgets.QToolButton(self.layoutWidget1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/arrow-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Right.setIcon(icon2)
        self.btn_Right.setIconSize(QtCore.QSize(25, 25))
        self.btn_Right.setObjectName("btn_Right")
        self.horizontalLayout_2.addWidget(self.btn_Right)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lne_Search = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Loma")
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lne_Search.setFont(font)
        self.lne_Search.setToolTip("")
        self.lne_Search.setStyleSheet("color: rgb(136, 138, 133);")
        self.lne_Search.setText("Search")
        self.lne_Search.setObjectName("lne_Search")
        self.verticalLayout.addWidget(self.lne_Search)
        self.lst_FilesList = QtWidgets.QListWidget(self.layoutWidget1)
        self.lst_FilesList.setObjectName("lst_FilesList")
        self.verticalLayout.addWidget(self.lst_FilesList)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(320, 50, 761, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.lbl_Date = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_Date.setFont(font)
        self.lbl_Date.setObjectName("lbl_Date")
        self.gridLayout.addWidget(self.lbl_Date, 0, 4, 1, 1)
        self.lbl_ID = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_ID.setFont(font)
        self.lbl_ID.setObjectName("lbl_ID")
        self.gridLayout.addWidget(self.lbl_ID, 0, 0, 1, 1)
        self.lbl_Sex = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_Sex.setFont(font)
        self.lbl_Sex.setObjectName("lbl_Sex")
        self.gridLayout.addWidget(self.lbl_Sex, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(310, 930, 261, 41))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lbl_y = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_y.setObjectName("lbl_y")
        self.gridLayout_2.addWidget(self.lbl_y, 0, 1, 1, 1)
        self.lbl_x = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_x.setObjectName("lbl_x")
        self.gridLayout_2.addWidget(self.lbl_x, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        self.btn_Trash = QtWidgets.QToolButton(self.centralwidget)
        self.btn_Trash.setGeometry(QtCore.QRect(670, 940, 41, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Trash.setIcon(icon3)
        self.btn_Trash.setIconSize(QtCore.QSize(25, 25))
        self.btn_Trash.setObjectName("btn_Trash")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(770, 900, 120, 88))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_ROI = QtWidgets.QPushButton(self.layoutWidget4)
        self.btn_ROI.setObjectName("btn_ROI")
        self.verticalLayout_2.addWidget(self.btn_ROI)
        self.btn_ROImage = QtWidgets.QPushButton(self.layoutWidget4)
        self.btn_ROImage.setObjectName("btn_ROImage")
        self.verticalLayout_2.addWidget(self.btn_ROImage)
        self.bar_predict1 = QtWidgets.QLabel(self.centralwidget)
        self.bar_predict1.setGeometry(QtCore.QRect(1150, 600, 301, 181))
        self.bar_predict1.setText("")
        self.bar_predict1.setObjectName("bar_predict1")
        self.bar_predict2 = QtWidgets.QLabel(self.centralwidget)
        self.bar_predict2.setGeometry(QtCore.QRect(1550, 600, 301, 181))
        self.bar_predict2.setText("")
        self.bar_predict2.setObjectName("bar_predict2")
        self.htmp_RK = QtWidgets.QLabel(self.centralwidget)
        self.htmp_RK.setGeometry(QtCore.QRect(1090, 210, 380, 380))
        self.htmp_RK.setText("")
        self.htmp_RK.setObjectName("htmp_RK")
        self.htmp_LK = QtWidgets.QLabel(self.centralwidget)
        self.htmp_LK.setGeometry(QtCore.QRect(1510, 210, 380, 380))
        self.htmp_LK.setText("")
        self.htmp_LK.setObjectName("htmp_LK")
        self.bar_predict_single = QtWidgets.QLabel(self.centralwidget)
        self.bar_predict_single.setGeometry(QtCore.QRect(1320, 650, 301, 181))
        self.bar_predict_single.setText("")
        self.bar_predict_single.setObjectName("bar_predict_single")
        self.htmp_single = QtWidgets.QLabel(self.centralwidget)
        self.htmp_single.setGeometry(QtCore.QRect(1230, 150, 500, 500))
        self.htmp_single.setText("")
        self.htmp_single.setObjectName("htmp_single")
        self.btn_Screenshot = QtWidgets.QToolButton(self.centralwidget)
        self.btn_Screenshot.setGeometry(QtCore.QRect(720, 940, 41, 41))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Screenshot.setIcon(icon4)
        self.btn_Screenshot.setIconSize(QtCore.QSize(25, 25))
        self.btn_Screenshot.setObjectName("btn_Screenshot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.mbr_Principal = QtWidgets.QMenuBar(MainWindow)
        self.mbr_Principal.setGeometry(QtCore.QRect(0, 0, 1918, 26))
        self.mbr_Principal.setObjectName("mbr_Principal")
        self.mnu_File = QtWidgets.QMenu(self.mbr_Principal)
        self.mnu_File.setObjectName("mnu_File")
        MainWindow.setMenuBar(self.mbr_Principal)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.mni_Open = QtWidgets.QAction(MainWindow)
        self.mni_Open.setObjectName("mni_Open")
        self.mni_Exit = QtWidgets.QAction(MainWindow)
        self.mni_Exit.setObjectName("mni_Exit")
        self.mnu_File.addAction(self.mni_Open)
        self.mnu_File.addSeparator()
        self.mnu_File.addAction(self.mni_Exit)
        self.mbr_Principal.addAction(self.mnu_File.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tesis"))
        self.Image.setWhatsThis(_translate("MainWindow", "Esto es una ventana"))
        self.btn_OpenFile.setText(_translate("MainWindow", "..."))
        self.btn_Left.setText(_translate("MainWindow", "..."))
        self.btn_Right.setText(_translate("MainWindow", "..."))
        self.lbl_Date.setText(_translate("MainWindow", "Date:"))
        self.lbl_ID.setText(_translate("MainWindow", "Name:"))
        self.lbl_Sex.setText(_translate("MainWindow", "Sex: "))
        self.lbl_y.setText(_translate("MainWindow", "Y:"))
        self.lbl_x.setText(_translate("MainWindow", "X:"))
        self.btn_Trash.setText(_translate("MainWindow", "..."))
        self.btn_ROI.setText(_translate("MainWindow", "ROI"))
        self.btn_ROImage.setText(_translate("MainWindow", "Process"))
        self.btn_Screenshot.setText(_translate("MainWindow", "..."))
        self.mnu_File.setTitle(_translate("MainWindow", "File"))
        self.mni_Open.setText(_translate("MainWindow", "Open"))
        self.mni_Open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.mni_Exit.setText(_translate("MainWindow", "Exit"))
        self.mni_Exit.setShortcut(_translate("MainWindow", "Ctrl+X"))

